basic_settings:
  site_title: "Freiheit und Gleichheit in der Bildungsgeschichte"
  site_subtitle: Jahrestagung der Sektion Historische Bildungsforschung
  site_subtitle_2: 11.–13. September 2023
  site_place: Berlin
  site_place_fjb: Humboldt-Universität zu Berlin
  description: …
  edit_url: https://github.com/klickmeister/edit/main

